### ISSUE TITLE
"Your magic goes here" comment issue

### ISSUE THREAD

**Issue by gel1os** [alex-kachura/UI-Fixer#3]
Comment is added even if field with script is not empty. It rewrites script in this case.

**Comment by oleksii-kachura** [comment]
Seems like it was a UI/browser bug, because there can't be prefilled script on Add new script page, but I've added a checker to exclude such possibility, just in case

**Comment by oleksii-kachura** [comment]
Found the same issue for description and campaign prefix on some pages. Fixed that in v.1.21
